# These are supported funding model platforms

github: GeauxWeisbeck4
patreon: GeauxWeisbeck4dev
open_collective: geauxweisbeck4
ko_fi: geauxweisbeck4
buy_me_a_coffee: geauxweisbeck4
# thanks_dev: # Replace with a single thanks.dev username
custom: [https://cash.app/lisaweisbeck4, https://venmo.com/lisaweisbeck4]
